---
title: "SocPop Analysis"
date: "8/9/2019"
output: html_document
---

---
Import necessary packages
---
```{r setup, include=FALSE}
library(tidyverse)
library(gridExtra)
library(brms)
library(knitr)
library(ggthemes)
library(bayesplot)
library(broom)

opts_chunk$set(echo=TRUE,
              warning=FALSE, message=FALSE,
              cache=FALSE)
```

## Read in data and create one dataframe with demographic and outcome information, assuming you already ran data_wrangling!
```{r}
data_label <- read_csv("./data/data_label.csv") %>% 
  select(-X1 )
comment_label <- read_csv("./data/comment_label.csv")

data_demo <- read_csv("./data/data_children.csv") %>% 
  mutate(id = as.character(id)) %>% 
  select(-c(child_born_US, dad_birth_country, dad_ed_L1_pre,
            DRT_L1_postKnown, DRT_L1_postKnownN, DRT_L1_postKnownSD, notGoodRT_L1_post_reason, 
            CDI_age_18m, CDI_understands_words_18m, CDI_produces_words_18m, CDI_age_25m)) %>% 
  rename("rt_25m" = "GoodDRT_L1_postKnown",
         "cdi_25m" = "CDI_vocab_25m",
         "rt_18m" = "GoodDRT_L1_preKnown",
         "ses" = "hi_L1_pre")


# merge into 1 dataframe
# note: 168 and 310 will be handcoded for their rt values
socpop <- data_label %>% 
  full_join(data_demo, by = "id")

```
## Models

### Reaction time as dependent variable

```{r}
# Prepare data file
# center predictors at 0 by subtracting mean to facilitate model fitting
# remove lines with NAs to allow centering

data_model <- socpop %>%
  filter(rt_25m != "NA",
         gestures != "NA",
         labels != "NA")%>%
  mutate(gestures = gestures - mean(gestures),
         labels = labels - mean(labels),
         labels_w_gestures = labels_w_gestures - mean(labels_w_gestures),
         rt_18m = rt_18m - mean(rt_18m),
         ses = ses - mean(ses))
```

#### Plotting DV

```{r}
# inspect DV - looks fine in this case
ggplot(data_model, aes(x=rt_25m))+
  geom_density()+
  xlim(0,2000)+
  theme_few()
```

#### Models

```{r}
# run models only when new data is added
# otherwise, you can just load the saved model output 
# saves time, each model takes approx. 2 min to run 
# when you run the model, the output is automatically saved
# even if you run the model, you need to load the saved file afterwards


# model_rt_label <- brm(rt_25m ~ labels + ses + rt_18m,
#                     data = data_model, family = gaussian(),
#           control = list(adapt_delta = 0.95),
#           save_all_pars = TRUE,
#           iter = 6000)%>%
#   add_criterion("waic")%>%
#   saveRDS("saves/model_rt_label.rds")

model_rt_label <- readRDS("saves/model_rt_label.rds")

# model_rt_gesture <- brm(rt_25m ~ gestures + ses + rt_18m,
#                     data = data_model, family = gaussian(),
#           control = list(adapt_delta = 0.95),
#           save_all_pars = TRUE,
#           iter = 6000)%>%
#   add_criterion("waic")%>%
#   saveRDS("saves/model_rt_gesture.rds")

model_rt_gesture <- readRDS("saves/model_rt_gesture.rds")

# model_rt_label_gesture <- brm(rt_25m ~ labels + gestures + ses + rt_18m,
#                     data = data_model, family = gaussian(),
#           control = list(adapt_delta = 0.95),
#           save_all_pars = TRUE,
#           iter = 6000)%>%
#   add_criterion("waic")%>%
#   saveRDS("saves/model_rt_label_gesture.rds")

model_rt_label_gesture <- readRDS("saves/model_rt_label_gesture.rds")

# model_rt_label_gesture_int <- brm(rt_25m ~ labels * gestures + ses + rt_18m,
#                     data = data_model, family = gaussian(),
#           control = list(adapt_delta = 0.95),
#           save_all_pars = TRUE,
#           iter = 6000)%>%
#   add_criterion("waic")%>%
#   saveRDS("saves/model_rt_label_gesture_int.rds")

model_rt_label_gesture_int <- readRDS("saves/model_rt_label_gesture_int.rds")

# model_rt_overlap <- brm(rt_25m ~ labels_w_gestures + ses + rt_18m,
#                     data = data_model, family = gaussian(),
#           control = list(adapt_delta = 0.95),
#           save_all_pars = TRUE,
#           iter = 6000)%>%
#   add_criterion("waic")%>%
#   saveRDS("saves/model_rt_overlap.rds")

model_rt_overlap <- readRDS("saves/model_rt_overlap.rds")

```

#### Model comparison

```{r}
# WAIC scores for each model
waic <- loo_compare(model_rt_label, 
                    model_rt_gesture,
                    model_rt_label_gesture,
                    model_rt_label_gesture_int,
                    model_rt_overlap, 
                    criterion = "waic")%>%
  as_tibble()%>%
  select(waic, se_waic)%>%
  round(2)

# WAIC weights
weights <-model_weights(model_rt_label, 
                    model_rt_gesture,
                    model_rt_label_gesture,
                    model_rt_label_gesture_int,
                    model_rt_overlap, 
                    weight = "waic")%>%
  as_tibble()%>%
  round(2)

# Putting things together in a dataframe
data_frame(
  model = c("label","gesture","label+gesture", "label*gesture","overlap"),
  WAIC = c(waic$waic[1],waic$waic[2],waic$waic[3],waic$waic[4],waic$waic[5]),
  SE = c(waic$se_waic[1],waic$se_waic[2],waic$se_waic[3],waic$se_waic[4],waic$se_waic[5]),
  weight = c(weights$value[1],weights$value[2],weights$value[3],weights$value[4],weights$value[5]))
```

```{r}
# inspect trace plots for models
# looks fine, check again when new data was added

# plot(model_rt_label)
# 
# plot(model_rt_gesture)
# 
# plot(model_rt_label_gesture)
# 
# plot(model_rt_label_gesture_int)
# 
# plot(model_rt_overlap)
```

#### Visualizing results

```{r}
# overview over model predictors
# removing intercept because it's on a different scale
# select models depending on results of model comparison

bind_rows(
tidy(model_rt_label)%>%mutate(model = "label"),
tidy(model_rt_gesture)%>%mutate(model = "gesture")#,
#tidy(model_rt_overlap)%>%mutate(model = "overlap"),
#tidy(model_rt_label_gesture)%>%mutate(model = "label+gesture"),
#tidy(model_rt_label_gesture_int)%>%mutate(model = "label*gesture")
) %>%
  filter(term != "b_Intercept",
         term != "sigma",
         term != "temp_Intercept",
         term != "lp__")%>% 
  mutate(term = str_remove(term,"b_"))%>%
  ggplot(aes(term, estimate, ymin = lower, ymax = upper, color = model)) + 
  geom_hline(yintercept=0)+
  geom_pointrange(position = position_dodge(width = .8))+
  coord_flip()+
  theme_few()+
  scale_color_ptol(name = "Model")
  
```









