---
title: "SocPop data wrangling"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)

```

```{r}
gesture <- read_csv("./data/data_200513_JB.csv", col_names = F) %>%
  rename(start = X3,
         stop = X4,
         tier = X1,
         ant = X6, 
         file = X7)%>%
  select(file, tier, start, stop, ant)%>%
  filter(tier == "Caregiver nonlinguistic") %>% 
  mutate(id = str_sub(file, 1, 3)) %>% 
  select(-file)

label <- read_csv("./data/data_200513_JB.csv", col_names = F) %>%
  rename(start = X3,
         stop = X4,
         tier = X1,
         ant = X6,
         file = X7)%>%
  select(file,tier, start, stop, ant)%>%
  filter(tier == "Caregiver linguistic", 
         ant != "english") %>% 
  mutate(id = str_sub(file, 1, 3)) %>% 
  select(-file)

comment <- read_csv("./data/elan_comments_cleanedV2_JB.csv") %>% 
  rename("stop" = 3, "id" = "subject") %>% 
  mutate(start = as.numeric(start), 
         stop = as.numeric(stop), 
         duration = as.numeric(duration)) %>% 
  mutate(start = round(start, 3), 
         stop = round(stop, 3), 
         duration = round(duration, 3),
         id = as.character(id),
         id = ifelse(id == "84", "084",id)) %>% 
  filter(tier == "Caregiver linguistic") %>% 
  dplyr::select(-c(comment))

```

# Gesture perspective

For each gesture, does it overlap with a label?

```{r}
overlap_ges <-  gesture %>%
  mutate(start = start -1 ,
         stop = stop + 1) %>%
  group_by(id, tier, start, stop) %>%
  expand(gesture_start = nesting(label$start,label$stop,label$id)) %>%
  filter(id == `label$id`)%>%
  mutate(overlap_start = ifelse(start <= `label$start` & stop >= `label$start`, T,F),
         overlap_stop = ifelse(start <= `label$stop` & stop >= `label$stop`, T,F))%>%
  group_by(id, tier, start, stop)%>%
  summarise(overlap_start = sum(overlap_start),
            overlap_stop = sum(overlap_stop))%>%
  mutate(overlap = ifelse(sum(overlap_start,overlap_stop) > 0, T,F))%>%
  group_by(id)%>%
  summarise(gestures_w_labels = sum(overlap))
         
gesture_sum <- gesture %>%
  group_by(id)%>%
  summarise(gestures = n())

label_sum <- label %>%
  group_by(id)%>%
  summarise(labels = n())

data_ges <- plyr::join_all(list(gesture_sum,label_sum,overlap_ges,relevant_sum), by='id', type='left') %>% 
  mutate_all(~replace(., is.na(.), 0)) # this replaces NA with 0, when there no gestures or labels

write.csv(data_ges, "./data/data_ges.csv")
```

# Label perspective

For each label, does it overlap with a gesture

```{r}
overlap_label <-  label %>%
  mutate(start = start -1 ,
         stop = stop + 1)%>%
  group_by(id, tier, start, stop)%>%
  expand(nesting(gesture$start,gesture$stop,gesture$id))%>%
  filter(id == `gesture$id`)%>%
  mutate(overlap_start = ifelse(start <= `gesture$start` & stop >= `gesture$start`, T,F),
         overlap_stop = ifelse(start <= `gesture$stop` & stop >= `gesture$stop`, T,F))%>%
  group_by(id, tier, start, stop)%>%
  summarise(overlap_start = sum(overlap_start),
            overlap_stop = sum(overlap_stop))%>%
  mutate(overlap = ifelse(sum(overlap_start,overlap_stop) > 0, T,F))%>%
  group_by(id)%>%
  summarise(labels_w_gestures = sum(overlap))
         
gesture_sum <- gesture %>%
  group_by(id)%>%
  summarise(gestures = n())

gesture_type_sum <- gesture %>%
  group_by(id, ant)%>%
  summarise(gestures = n())%>%
  spread(ant, gestures)%>%
  replace(is.na(.), 0)%>%
  rename(iconic = `descriptive or iconic gesture`, 
         point = `extended index finger`,
         hold_out = `hold out/give`, 
         touch = `touching w/ open hand`)

overlap_relevant <-  comment %>%
  filter(relevance == 1)%>%
  mutate(start = start -1 ,
         stop = stop + 1)%>%
  group_by(id,relevance, tier, start, stop)%>%
  expand(nesting(gesture$start,gesture$stop,gesture$id))%>%
  filter(id == `gesture$id`)%>%
  mutate(overlap_start = ifelse(start <= `gesture$start` & stop >= `gesture$start`, T,F),
         overlap_stop = ifelse(start <= `gesture$stop` & stop >= `gesture$stop`, T,F))%>%
  group_by(id, tier, start, stop)%>%
  summarise(overlap_start = sum(overlap_start),
            overlap_stop = sum(overlap_stop))%>%
  mutate(overlap = ifelse(sum(overlap_start,overlap_stop) > 0, T,F))%>%
  group_by(id)%>%
  summarise(labels_w_rel_gestures = sum(overlap))

label_sum <- label %>%
  group_by(id)%>%
  summarise(labels = n())

data_label <- plyr::join_all(list(gesture_sum,label_sum,overlap_label,gesture_type_sum,overlap_relevant), by='id', type='left') %>% 
  mutate_all(~replace(., is.na(.), 0)) # this replaces NA with 0, when there no gestures or labels

write.csv(data_label, "./data/input.csv")
```

# Merge all gestures, labels, and comments into one dataframe

```{r}
label_sp_en <- read_csv("./data/data_200513_JB.csv", col_names = F) %>%
  rename(start = X3,
         stop = X4,
         tier = X1,
         ant = X6,
         file = X7)%>%
  select(file,tier, start, stop, ant)%>%
  filter(tier == "Caregiver linguistic") %>% 
  mutate(id = str_sub(file, 1, 3)) %>% 
  select(-file)

# note there are some labels (n = 15 children) with missing comments and relevance tags, so we will merge on all labels with comments
# most children are only missing 1 to 2 comments, with one missing 3 comments (433)
# for now we will join on those with comments, but to see which children are missing comments do full_join
comment_label <- comment %>% 
  left_join(label_sp_en, by = c("id", "start", "stop", "tier")) %>% 
  filter(ant != "english")

write.csv(comment_label, "./data/comment_label.csv")
```

