---
title: "SocPop reliability"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(irr)

```

#  Primary coder (rater 1)

## Read data

```{r}
gesture_prim <- read_tsv("./data/reliability_test_JR.txt", col_names = F)%>%
  rename(start = X3,
         stop = X4,
         code = X1,
         id = X7)%>%
  select(id,code, start,stop)%>%
  filter(code == "Caregiver nonlinguistic")


label_prim <- read_tsv("./data/reliability_test_JR.txt", col_names = F)%>%
  rename(start = X3,
         stop = X4,
         code = X1,
         id = X7)%>%
  select(id,code, start,stop)%>%
  filter(code == "Caregiver linguistic")

```

## Compute number of gestures labels and overlab (from laber perspective)

```{r}
overlap_label_prim <-  label_prim %>%
  mutate(start = start -1 ,
         stop = stop + 1)%>%
  group_by(id, code, start, stop)%>%
  expand(gesture_start = nesting(gesture_prim$start,gesture_prim$stop,gesture_prim$id))%>%
  filter(id == `gesture_prim$id`)%>%
  mutate(overlap_start = ifelse(start <= `gesture_prim$start` & stop >= `gesture_prim$start`, T,F),
         overlap_stop = ifelse(start <= `gesture_prim$stop` & stop >= `gesture_prim$stop`, T,F))%>%
  group_by(id, code, start, stop)%>%
  summarise(overlap_start = sum(overlap_start),
            overlap_stop = sum(overlap_stop))%>%
  mutate(overlap = ifelse(sum(overlap_start,overlap_stop) > 0, T,F))%>%
  group_by(id)%>%
  summarise(labels_w_gestures_prim = sum(overlap))
         
gesture_sum_prim <- gesture_prim %>%
  group_by(id)%>%
  summarise(gestures_prim = n())

label_sum_prim <- label_prim %>%
  group_by(id)%>%
  summarise(labels_prim = n())

data_label_primary <- plyr::join_all(list(gesture_sum_prim,label_sum_prim,overlap_label_prim), by=c("id"), type='left')%>%
  mutate(id = substr(id,1, nchar(id)-14))
```

# Consensus files (rater 2)

## Read data

```{r}
gesture <- read_tsv("./data/reliability_test.txt", col_names = F)%>%
  rename(start = X3,
         stop = X4,
         code = X1,
         id = X7)%>%
  select(id,code, start,stop)%>%
  filter(code == "Caregiver nonlinguistic")


label <- read_tsv("./data/reliability_test.txt", col_names = F)%>%
  rename(start = X3,
         stop = X4,
         code = X1,
         id = X7)%>%
  select(id,code, start,stop)%>%
  filter(code == "Caregiver linguistic")

```

## Compute number of gestures labels and overlab (from laber perspective)

```{r}
overlap_label <-  label %>%
  mutate(start = start -1 ,
         stop = stop + 1)%>%
  group_by(id, code, start, stop)%>%
  expand(gesture_start = nesting(gesture$start,gesture$stop,gesture$id))%>%
  filter(id == `gesture$id`)%>%
  mutate(overlap_start = ifelse(start <= `gesture$start` & stop >= `gesture$start`, T,F),
         overlap_stop = ifelse(start <= `gesture$stop` & stop >= `gesture$stop`, T,F))%>%
  group_by(id, code, start, stop)%>%
  summarise(overlap_start = sum(overlap_start),
            overlap_stop = sum(overlap_stop))%>%
  mutate(overlap = ifelse(sum(overlap_start,overlap_stop) > 0, T,F))%>%
  group_by(id)%>%
  summarise(labels_w_gestures_reli = sum(overlap))
         
gesture_sum <- gesture %>%
  group_by(id)%>%
  summarise(gestures_reli = n())

label_sum <- label %>%
  group_by(id)%>%
  summarise(labels_reli = n())

data_label_reli <- plyr::join_all(list(gesture_sum,label_sum,overlap_label), by=c("id"), type='left')%>%
  mutate(id = substr(id,1, nchar(id)-21))
```


# Reliability

## joining data files
```{r}
rel <- left_join(data_label_reli, data_label_primary, by = "id")
```

## gesture
```{r}
icc(rel%>%select(gestures_reli,gestures_prim), model = "oneway")
```

## labels
```{r}

icc(rel%>%select(labels_reli,labels_prim), model = "oneway")

```

## overlap
```{r}

icc(rel%>%select(labels_w_gestures_reli,labels_w_gestures_prim), model = "oneway")

```
