---
title: "SocPop Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(gridExtra)
library(brms)
library(knitr)
library(ggthemes)
library(bayesplot)
library(broom)
library(corrr)
library(ggcorrplot)
library(readxl)
library(ggpubr)
library(lsr)
library(tidyboot)
library(tidybayes)
library(gmodels)

opts_chunk$set(echo=F,
              warning=FALSE, message=FALSE,
              cache=FALSE, fig.align = "center")
```

# figure of 3 different caregivers
```{r}
df_n3 <- read_csv("./data/data_for_n3_fig.csv", col_names = T) %>% 
  mutate(id = ifelse(str_detect(id, "Caregiver 1"), "Caregiver 1: average number of labels and gestures",
              ifelse(str_detect(id, "Caregiver 2"), "Caregiver 2: above average number of labels and below average number of gestures", 
              ifelse(str_detect(id, "Caregiver 3"), "Caregiver 3: above average number of labels and gestures", "CHECK"))))


# count of labels and gestures for those in figure
df_n3 %>% group_by(id) %>% count(behavior)

ggplot(df_n3, aes(colour = behavior)) + 
  geom_segment(aes(x = start, xend = stop, y = behavior, yend = behavior), size=3) +
  labs(x = "\nTime (s)", y = "") + 
  facet_wrap(~ id, ncol = 1) + 
  theme_minimal() + 
  theme(legend.position = "none",
        axis.text = element_text(size = 13),
        axis.title = element_text(size = 13),
        strip.text.x = element_text(size = 13))

ggsave("./figures/fig.durations.png", height = 4, width = 8 , scale = 1.5)

```




```{r}
input <- read_csv("./data/data_iv.csv")

data <- read_excel("./data/data_dv.xlsx") %>% 
  mutate(id = as.character(id)) %>% 
  select(c(id, L1PRE_mom_ed,
           L1PRE_hi, 
           L1PRE_gooddrt, L1POST_gooddrt, L1PRE_goodacc_3001800, L1POST_goodacc_3001800,
           L1PRE_cdi_version, age_L1PRE, L1PRE_cdi_vocab, age_L1POST, L1POST_cdi_vocab, 
           L1PRE_PS_AWChr)) %>% 
  mutate(L1PRE_cdi_vocab = as.numeric(L1PRE_cdi_vocab), 
         cdi_18m = ifelse(L1PRE_cdi_version == "wg", (L1PRE_cdi_vocab * 396 / 680), 
                   ifelse(L1PRE_cdi_version == "ws", L1PRE_cdi_vocab, "CHECK")), 
         cdi_18m = round(as.numeric(cdi_18m), digits = 0)) %>% 
  select(-c(L1PRE_cdi_version, L1PRE_cdi_vocab)) %>% 
  rename(rt_18m = L1PRE_gooddrt,
         rt_25m = L1POST_gooddrt, cdi_25m = L1POST_cdi_vocab,
         acc_18m = L1PRE_goodacc_3001800, 
         acc25m = L1POST_goodacc_3001800,
         ses_18m = L1PRE_hi, awc_phr_18m = L1PRE_PS_AWChr, 
         mom_ed_18m = L1PRE_mom_ed, 
         age_18m = age_L1PRE, age_25m = age_L1POST)

# merge into 1 dataframe
socpop <- input %>% 
  full_join(data, by = "id") %>%
  select(-X1)%>%
  mutate(cdi_25m = as.numeric(cdi_25m),
         cdi_18m = as.numeric(cdi_18m),
         labels_me_rel = labels - labels_w_rel_gestures,
         labels_me = labels - labels_w_gestures,
         prop_lab_ges = labels_w_gestures/labels)

```

### Predictors vs DVs

```{r, fig.width=12, fig.height=8}
socpop %>%
  select(id, gestures, labels, labels_w_gestures,awc_phr_18m, rt_25m, cdi_25m)%>%
  gather(DV, y, -id, -gestures,-labels_w_gestures,-awc_phr_18m, -labels)%>%
  gather(input, freq, -id, -DV, -y)%>%
  mutate(DV = factor(DV, levels = c("rt_25m", "cdi_25m"), labels = c("Reaction Time (25m)", "Vocabulary Size (25m)")), 
         input = factor(input,levels = c("labels", "awc_phr_18m", "labels_w_gestures", "gestures"), labels = c("Labels (18m)","Adult Words per Hour (18m)", "Label-Gesture Overlap (18m)", "Gestures (18m)")),
         y = as.numeric(y)) %>%
  ggplot(aes(x = freq, y = y))+
  geom_point(alpha = 0.5)+
  facet_grid(DV~input, scales = "free", switch = "y")+
  geom_smooth(method = "lm", lty = 2, col = "black")+
  stat_cor(method = "pearson", vjust = .5, aes(label = ..r.label..), label.x = 3)+
  labs(y = "", x = "Frequency") + 
  theme_few(base_size = 12)+
  theme(strip.placement = "outside")

ggsave("./figures/fig.1a.png", height = 4, width = 8 , scale = 1.5)

```


```{r}
socpop %>%
  select(gestures, labels, labels_w_gestures,awc_phr_18m, rt_25m, cdi_25m)%>%
  corrr::correlate(method ="pearson", use = "pairwise.complete.obs")%>%
  gather(task, cor, -rowname)%>%
  filter(rowname == "rt_25m" | rowname == "cdi_25m")%>%
  mutate_if(is.numeric, round, digits = 2)%>%
  na.omit()%>%
  filter(task != "rt_25m", 
         task != "cdi_25m")%>%
  mutate(rowname = factor(rowname, levels = c("cdi_25m","rt_25m"), labels = c("Vocabulary Size (25m)","Reaction Time (25m)")), 
         task = factor(task,levels = c("labels", "awc_phr_18m", "labels_w_gestures", "gestures"), labels = c("Labels (18m)","Adult Words per Hour (18m)", "Label-Gesture Overlap (18m)", "Gestures (18m)")))%>%
  ggplot(., aes(y = rowname, x = task, fill = cor))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Correlation") +
   coord_fixed()+
  theme_few(base_size = 12)+
  geom_text(aes(label = cor), color = "black", size = 3) +
  theme(#legend.justification = c(1, 0),
        #legend.position = c(0.55, 0.7),
        legend.position = "right",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))

ggsave("./figures/fig.1b.png", height = 3, width = 6 , scale = 1.5)
```

```{r}
fig_1_a <- socpop %>%
  select(gestures, labels, labels_w_gestures, awc_phr_18m)%>%
  rename(`Labels (18m)` = labels,
         `Gestures (18m)` = gestures,
         `Adult Words per Hour (18m)` = awc_phr_18m,
         `Label-Gesture Overlap (18m)` = labels_w_gestures
  )%>%
  gather(Input, Count)%>%
  mutate(Input = factor(Input, levels = c( "Adult Words per Hour (18m)","Labels (18m)", "Gestures (18m)", "Label-Gesture Overlap (18m)")))%>%
  group_by(Input)%>%
  mutate(mean = ci(Count, na.rm = T)[1],
         l_ci = ci(Count, na.rm = T)[2],
         u_ci = ci(Count, na.rm = T)[3]
         )%>%
ggplot(aes(x= Count))+
  geom_histogram(colour="black", fill="white")+
  geom_point(aes(x = mean, y = -0.25), col = "#FF6666")+
  geom_errorbarh(aes(xmin = l_ci, xmax = u_ci, y = -0.25), col = "#FF6666", height = 0)+
  ylim(-0.5,6)+
  #geom_density(alpha=.2, fill="#FF6666")+
  facet_wrap(~Input, scales = "free_x")+
  labs(y = "Count", x = "No occurences in Play Session")+
  theme_minimal()
  

ggsave("./figures/fig.1d.png", height = 4, width = 5 , scale = 1)
```


```{r}
fig_1_b <- socpop %>%
  select(ses_18m, rt_18m, cdi_18m, gestures, labels, labels_w_gestures,awc_phr_18m, rt_25m, cdi_25m)%>%
  rename(`SES (18m)` = ses_18m,
         `Vocabulary Size (18m)` = cdi_18m,
         `Reaction Time (18m)` = rt_18m,
         `Labels (18m)` = labels,
         `Gestures (18m)` = gestures,
         `Adult Words per Hour (18m)` = awc_phr_18m,
         `Label-Gesture Overlap (18m)` = labels_w_gestures, 
         `Vocabulary Size (25m)` = cdi_25m,
         `Reaction Time (25m)` = rt_25m, 
  )%>%
  cor(method ="pearson", use = "pairwise.complete.obs")%>%
  ggcorrplot::ggcorrplot(method="circle",type="lower", show.diag = F, lab = TRUE, digits = 2, lab_size = 2,tl.cex = 8 )+
  scale_fill_gradientn(colours = colorRampPalette(c("#CC6677","white","#117733"))(200), limits = c(-1,1), name = "Correlation")+
  theme(text = element_text(size=8),
        legend.position = "top",
        axis.text.x = element_text(angle=35))+
  theme(legend.position = "right")

ggarrange(fig_1_a, fig_1_b, labels = c("A","B"))  

ggsave("./figures/fig.1ab.png", height = 4, width = 10 , scale = 1)

```


# Models RT

```{r,echo= F, echo = F}

 model_rt_label <- readRDS("saves/model_rt_label.rds")

 model_rt_awc <- readRDS("saves/model_rt_awc.rds")
 
 model_rt_gesture <- readRDS("saves/model_rt_gesture.rds")

 model_rt_label_gesture <- readRDS("saves/model_rt_label_gesture.rds")

 model_rt_label_gesture_int <- readRDS("saves/model_rt_label_gesture_int.rds")

 model_rt_overlap <- readRDS("saves/model_rt_overlap.rds")

 model_rt_null <- readRDS("saves/model_rt_null.rds")

```

```{r}
data_model <- socpop %>%
  filter(rt_25m != "NA",
         gestures != "NA",
         labels != "NA")%>%
  mutate(gestures = scale(gestures, center = TRUE, scale = T),
         labels_z = scale(labels, center = TRUE, scale = T),
         labels_w_gestures = scale(labels_w_gestures, center = TRUE, scale = T),
         labels_w_rel_gestures = scale(labels_w_rel_gestures, center = TRUE, scale = T),
         labels_me = scale(labels_me, center = TRUE, scale = T),
         awc_phr_18m = scale(awc_phr_18m, center = TRUE, scale = T),
         rt_18m = scale(rt_18m, center = TRUE, scale = T),
         ses_18m = scale(ses_18m, center = TRUE, scale = T))

## plot expected predictions against actual response
```

```{r}
ggplot(data = fit_label_rt, aes(x = rt_25m, y = Estimate))+
  geom_abline(linetype = 2, color = "grey50", size = .5) +
  geom_point(size = 1.5, color = "firebrick4", alpha = 3/4) +
  geom_linerange(aes(ymin = Q2.5, ymax = Q97.5),
                 size = 1/4, color = "firebrick4") +
  geom_linerange(aes(ymin = Estimate - Est.Error, 
                     ymax = Estimate + Est.Error),
                 size = 1/2, color = "firebrick4")+
  xlim(range(data_model$rt_25m))+
  ylim(range(data_model$rt_25m))+
  labs(x = "Observed Reaction Time", 
       y = "Predicted Reaction Time")+
  theme_minimal()
```


### Models CDI

```{r, echo = F}

model_cdi_label <- readRDS("saves/model_cdi_label.rds")
 
model_cdi_awc <- readRDS("saves/model_cdi_awc.rds")

model_cdi_gesture <- readRDS("saves/model_cdi_gesture.rds")

model_cdi_label_gesture <- readRDS("saves/model_cdi_label_gesture.rds")

model_cdi_label_gesture_int <- readRDS("saves/model_cdi_label_gesture_int.rds")

model_cdi_overlap <- readRDS("saves/model_cdi_overlap.rds")

model_cdi_null <- readRDS("saves/model_cdi_null.rds")

```

# Model comparison 

```{r}
# Putting things together in a dataframe
# BF = Bayes factor in favor of the winning model in this case label

rt_model_comp <- loo_compare(model_rt_label, 
            model_rt_awc,
            model_rt_gesture,
            model_rt_label_gesture,
            model_rt_label_gesture_int,
            model_rt_overlap,
            model_rt_null,
            criterion = "waic")%>%
  as.data.frame()%>%
  tibble::rownames_to_column("Model")%>%
  mutate(Model = str_replace(Model, "model_rt_", ""),
         waic = round(waic, 2),
         se_waic = round(se_waic, 2),
         weight = exp(elpd_waic)/sum(exp(elpd_waic)),
         weight = round(weight, 3))%>%
  select(Model, waic, se_waic, weight)%>%
  arrange(-waic)%>%
  mutate(Model=factor(Model, levels=Model),
         DV = "Reaction Time")%>%
  mutate(Model = recode(Model,
                        label = "Labels",
                        gesture = "Gestures" ,
                        label_gesture = "Labels + Gestures",
                        label_gesture_int = "Labels * Gestures",
                        overlap = "Label-Gesture Overlap",
                        awc = "Adult Words per Hour",
                        null = "Baseline (Covariates)"))




cdi_model_comp <- loo_compare(
  model_cdi_label,
  model_cdi_awc,
            model_cdi_gesture,
            model_cdi_label_gesture,
            model_cdi_label_gesture_int,
            model_cdi_overlap,
            model_cdi_null,
            criterion = "waic")%>%
  as.data.frame()%>%
  tibble::rownames_to_column("Model")%>%
  mutate(Model = str_replace(Model, "model_cdi_", ""),
         waic = round(waic, 2),
         se_waic = round(se_waic, 2),
         weight = exp(elpd_waic)/sum(exp(elpd_waic)),
         weight = round(weight, 3)
         #bf = c("-", round(bf_cdi_1$bf,2),round(bf_cdi_3$bf,2),round(bf_cdi_4$bf,2),round(bf_cdi_1$bf,2))
         )%>%
  select(Model, waic, se_waic, weight)%>%
  arrange(-waic)%>%
  mutate(Model=factor(Model, levels=Model),
         DV = "Vocabulary Size")%>%
  mutate(Model = recode(Model,
                        label = "Labels",
                        gesture = "Gestures" ,
                        label_gesture = "Labels + Gestures",
                        label_gesture_int = "Labels * Gestures",
                        overlap = "Label-Gesture Overlap",
                        awc = "Adult Words per Hour",
                        null = "Baseline (Covariates)"))

order <- tibble(DV = c( "Reaction Time","Vocabulary Size"))%>%
  mutate(DV = factor(DV, levels=c("Reaction Time","Vocabulary Size")))
  

```

```{r}
ggplot()+
      geom_bar(data = rt_model_comp, aes(fill=Model, y=weight, x = DV, label = waic), position="stack", stat="identity", width = .5, alpha = .8)+
  geom_text(data = rt_model_comp, aes(fill=Model, y=weight, x = DV, label = waic),size = 3, position = position_stack(vjust = 0.5),angle = 90)+
  geom_bar(data = cdi_model_comp, aes(fill=Model, y=weight, x = DV, label = waic), position="stack", stat="identity", width = .5, alpha = .8)+
  geom_text(data = cdi_model_comp, aes(fill=Model, y=weight, x = DV, label = waic),size = 3, position = position_stack(vjust = 0.5),angle = 90)+
  labs(x = "", y = "Model Weights (WAIC)")+
  scale_fill_ptol(name = "Model (Test Predictor)")+
  theme_minimal()+
  guides(fill = guide_legend(reverse = TRUE))+
  coord_flip()+
  scale_x_discrete(limits =c("Vocabulary Size","Reaction Time"))

ggsave("./figures/fig.2.png", height = 3, width = 10 , scale = 1)
```

#### Visualizing model parameters RT

```{r}

plot_pred_rt_label <- model_rt_label %>%
  gather_draws(b_labels, b_ses_18m, b_rt_18m)%>%
  mutate(Predictor = recode(.variable,
                        b_labels = "Labels at 18m",
                        b_ses_18m = "SES at 18m" ,
                        b_rt_18m = "Reaction Time at 18m"),
         Predictor = factor(Predictor, levels = c("Labels at 18m","Reaction Time at 18m","SES at 18m")))%>%
  ggplot(aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
  stat_halfeye(alpha = .7, .width = c(.95, .80)) +
    labs(x = "Model Estimate", y ="")+
  guides(fill = F)+
  ggtitle("DV: Reaction Time (25m)")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_manual(values = c("#85AD00","grey"))+
  theme_minimal()+
  theme(legend.position = "bottom")+ 
  theme(plot.title = element_text(hjust=-0.2))

plot_pred_cdi_label <- model_cdi_label %>%
  gather_draws(b_labels, b_ses_18m, b_cdi_18m)%>%
  mutate(Predictor = recode(.variable,
                        b_labels = "Labels at 18m",
                        b_ses_18m = "SES at 18m" ,
                        b_cdi_18m = "Vocabulary Size at 18m"),
         Predictor = factor(Predictor, levels = c("Labels at 18m","Vocabulary Size at 18m","SES at 18m")))%>%
  ggplot(aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
  stat_halfeye(alpha = .7, .width = c(.95, .80)) +
  labs(x = "Model Estimate", y ="")+
  guides(fill = F)+
  ggtitle("DV: Vocabulary Size (25m)")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_manual(values = c("grey","#85AD00"))+
  theme_minimal()+
  theme(legend.position = "bottom")+ 
  theme(plot.title = element_text(hjust=-0.2))


```


```{r}
fit_label_rt <- 
  fitted(model_rt_label) %>%
  as_tibble() %>%
  bind_cols(data_model)%>%
  mutate(model = "Labels")

plot_fit_rt_label <- ggplot(data = fit_label_rt, aes(x = labels, y = rt_25m)) +
  geom_segment(aes(xend = labels, yend = Estimate), 
               size = 1/2, col = "grey")+
  geom_point(size = 2, shape = 1)+
  geom_point(aes(y = Estimate), color = "firebrick4",size = 2, shape = 1)+
  labs(x = "Labels at 18m", 
       y = "Reaction Time at 25m")+
  coord_cartesian(ylim = range(data_model$rt_25m)) +
  theme_minimal()

```

```{r}
data_cdi_model <- socpop %>%
  filter(cdi_18m != "NA",
         cdi_25m != "NA",
         gestures != "NA",
         labels != "NA")%>%
  mutate(gestures = scale(gestures, center = TRUE, scale = T),
         labels_z = scale(labels, center = TRUE, scale = T),
         labels_w_gestures = scale(labels_w_gestures, center = TRUE, scale = T),
         labels_w_rel_gestures = scale(labels_w_rel_gestures, center = TRUE, scale = T),
         labels_me = scale(labels_me, center = TRUE, scale = T),
         cdi_18m = scale(cdi_18m, center = TRUE, scale = T),
         ses_18m = scale(ses_18m, center = TRUE, scale = T),
                  awc_phr_18m = scale(awc_phr_18m, center = TRUE, scale = T))
```

```{r}
fit_label_cdi <- 
  fitted(model_cdi_label) %>%
  as_tibble() %>%
  bind_cols(data_cdi_model)%>%
  mutate(model = "Labels")

plot_fit_cdi_label <- ggplot(data = fit_label_cdi, aes(x = labels, y = cdi_25m)) +
  geom_segment(aes(xend = labels, yend = Estimate), 
               size = 1/2, col = "grey")+
  geom_point(aes(col = "black"),size = 2, shape = 1)+
  geom_point(aes(y = Estimate,color = "firebrick4"),size = 2, shape = 1)+
      labs(x = "Labels at 18m", 
       y = "Vocabulary Size at 25m")+
  coord_cartesian(ylim = range(data_cdi_model$cdi_25m)) +
  scale_y_continuous(breaks = c(0,200,400))+
  theme_minimal()+
  scale_colour_manual(name="", labels = c("Predicted","Observed"), values = c("firebrick4","black"))+
  theme(legend.position = c(0.9,.2))

```

```{r}
ggplot(data = fit_cdi, aes(x = cdi_25m, y = Estimate))+
  geom_abline(linetype = 2, color = "grey50", size = .5) +
  geom_point(size = 1.5, color = "firebrick4", alpha = 3/4) +
  geom_linerange(aes(ymin = Q2.5, ymax = Q97.5),
                 size = 1/4, color = "firebrick4") +
  geom_linerange(aes(ymin = Estimate - Est.Error, 
                     ymax = Estimate + Est.Error),
                 size = 1/2, color = "firebrick4")+
  xlim(range(data_model$cdi_25m))+
  ylim(range(data_model$cdi_25m))+
  labs(x = "Observed Reaction Time", 
       y = "Predicted Reaction Time")+
  theme_minimal()
```

```{r}
ggarrange(
  plot_pred_rt_label,
  plot_fit_rt_label,
  plot_pred_cdi_label,
  plot_fit_cdi_label,
  ncol = 2, 
  nrow = 2,
  labels = c("A-i","A-ii","B-i","B-ii")
)
```

```{r}
ggsave("./figures/fig.3.png", height = 4.5, width = 8 , scale = 1.4)
```

# Labels and gestures across models
```{r}
plot_pred_rt_label <- model_rt_label %>%
  gather_draws(b_labels, b_ses_18m, b_rt_18m)%>%
  mutate(Predictor = recode(.variable,
                        b_labels = "Labels at 18m",
                        b_ses_18m = "SES at 18m" ,
                        b_rt_18m = "Reaction Time at 18m"),
  Predictor = factor(Predictor, levels = c("Labels at 18m","Reaction Time at 18m","SES at 18m")))

pred_comp <- bind_rows(
broom.mixed::tidy(model_rt_label) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Reaction Time", Model = "Labels"),
broom.mixed::tidy(model_rt_gesture) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Reaction Time", Model = "Gestures"),
broom.mixed::tidy(model_rt_label_gesture) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Reaction Time", Model = "Labels + Gestures"),
broom.mixed::tidy(model_rt_label_gesture_int) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Reaction Time", Model = "Labels * Gestures"),


broom.mixed::tidy(model_cdi_label) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Vocabulary Size", Model = "Labels"),
broom.mixed::tidy(model_cdi_gesture) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Vocabulary Size", Model = "Gestures"),
broom.mixed::tidy(model_cdi_label_gesture) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Vocabulary Size", Model = "Labels + Gestures"),
broom.mixed::tidy(model_cdi_label_gesture_int) %>% filter(term == "labels" | term == "gestures" | term == "labels:gestures")%>% mutate(DV = "Vocabulary Size", Model = "Labels * Gestures"),

)%>%
  filter(term != "labels:gestures")%>%
  mutate(Model = factor(Model, levels = c("Labels","Gestures", "Labels + Gestures", "Labels * Gestures")),
         Predictor = factor(term, levels = c("labels", "gestures", "labels:gestures"), labels = c("Labels", "Gestures", "Labels * Gestures")))


ggplot(data = pred_comp, aes(y = estimate, x = Predictor, col = Model)) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high), position = position_dodge(width = .8))+
  facet_grid(~DV)+
  ylab("Estimate")+
  theme_minimal()+
  coord_flip()+
  scale_color_manual( values = c("#AA4499", "#88CCEE","#CC6677","#44AA99"))+
  theme(legend.position = "bottom", axis.title.x=element_blank(), axis.title.y=element_blank())
```
```{r}
ggsave("./figures/fig.4.png", height = 2, width = 5 , scale = 1.4)
```
